name: Run Python examples

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install uxsim and dependencies
      run: pip install .
    - name: Install pytest other dependencies
      run: pip install pytest setuptools gymnasium torch
    - name: Run examples with pytest
      run: pytest demos_and_examples/test_examples.py --durations=0
